/*Copyright (c) 2016-2017 testing.com All Rights Reserved.
 This software is the confidential and proprietary information of testing.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with testing.com*/

package com.sharedtestproject.classicmodels;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import javax.persistence.PrimaryKeyJoinColumn;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;


import java.util.Arrays;

import javax.persistence.Transient;
import javax.persistence.CascadeType;
import javax.persistence.UniqueConstraint;



/**
 * Offices generated by hbm2java
 */
@Entity
@Table(name="`offices`"
)

public class Offices  implements java.io.Serializable {

    
    private String officeCode;
    
    private String city;
    
    private String phone;
    
    private String addressLine1;
    
    private String addressLine2;
    
    private String state;
    
    private String country;
    
    private String postalCode;
    
    private String territory;
    
    private Set<Employees> employeeses = new HashSet<Employees>(0);

    public Offices() {
    }


    @Id 
    

    @Column(name="`officeCode`", length=10)
    public String getOfficeCode() {
        return this.officeCode;
    }
    
    public void setOfficeCode(String officeCode) {
        this.officeCode = officeCode;
    }

    

    @Column(name="`city`", length=50)
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }

    

    @Column(name="`phone`", length=50)
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }

    

    @Column(name="`addressLine1`", length=50)
    public String getAddressLine1() {
        return this.addressLine1;
    }
    
    public void setAddressLine1(String addressLine1) {
        this.addressLine1 = addressLine1;
    }

    

    @Column(name="`addressLine2`", length=50)
    public String getAddressLine2() {
        return this.addressLine2;
    }
    
    public void setAddressLine2(String addressLine2) {
        this.addressLine2 = addressLine2;
    }

    

    @Column(name="`state`", length=50)
    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }

    

    @Column(name="`country`", length=50)
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }

    

    @Column(name="`postalCode`", length=15)
    public String getPostalCode() {
        return this.postalCode;
    }
    
    public void setPostalCode(String postalCode) {
        this.postalCode = postalCode;
    }

    

    @Column(name="`territory`", length=10)
    public String getTerritory() {
        return this.territory;
    }
    
    public void setTerritory(String territory) {
        this.territory = territory;
    }

    @OneToMany(fetch=FetchType.LAZY, cascade = {CascadeType.ALL}, mappedBy="offices")
    public Set<Employees> getEmployeeses() {
        return this.employeeses;
    }
    
    public void setEmployeeses(Set<Employees> employeeses) {
        this.employeeses = employeeses;
    }





    public boolean equals(Object o) {
         if (this == o) return true;
		 if ( (o == null )) return false;
		 if ( !(o instanceof Offices) )
		    return false;

		 Offices that = (Offices) o;

		 return ( (this.getOfficeCode()==that.getOfficeCode()) || ( this.getOfficeCode()!=null && that.getOfficeCode()!=null && this.getOfficeCode().equals(that.getOfficeCode()) ) );
    }

    public int hashCode() {
         int result = 17;

         result = 37 * result + ( getOfficeCode() == null ? 0 : this.getOfficeCode().hashCode() );

         return result;
    }


}

