/*Copyright (c) 2016-2017 testing.com All Rights Reserved.
 This software is the confidential and proprietary information of testing.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with testing.com*/

package com.sharedtestproject.classicmodels;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import javax.persistence.PrimaryKeyJoinColumn;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;


import java.util.Arrays;

import javax.persistence.Transient;
import javax.persistence.CascadeType;
import javax.persistence.UniqueConstraint;



/**
 * Orders generated by hbm2java
 */
@Entity
@Table(name="`orders`"
)

public class Orders  implements java.io.Serializable {

    
    private Integer orderNumber;
    
    private Date orderDate;
    
    private Date requiredDate;
    
    private Date shippedDate;
    
    private String status;
    
    private String comments;
    
    private Customers customers;
    
    private Set<Orderdetails> orderdetailses = new HashSet<Orderdetails>(0);

    public Orders() {
    }


    @Id 
    

    @Column(name="`orderNumber`", precision=10)
    public Integer getOrderNumber() {
        return this.orderNumber;
    }
    
    public void setOrderNumber(Integer orderNumber) {
        this.orderNumber = orderNumber;
    }

    @Temporal(TemporalType.DATE)

    @Column(name="`orderDate`", length=10)
    public Date getOrderDate() {
        return this.orderDate;
    }
    
    public void setOrderDate(Date orderDate) {
        this.orderDate = orderDate;
    }

    @Temporal(TemporalType.DATE)

    @Column(name="`requiredDate`", length=10)
    public Date getRequiredDate() {
        return this.requiredDate;
    }
    
    public void setRequiredDate(Date requiredDate) {
        this.requiredDate = requiredDate;
    }

    @Temporal(TemporalType.DATE)

    @Column(name="`shippedDate`", length=10)
    public Date getShippedDate() {
        return this.shippedDate;
    }
    
    public void setShippedDate(Date shippedDate) {
        this.shippedDate = shippedDate;
    }

    

    @Column(name="`status`", length=15)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    

    @Column(name="`comments`", length=65535)
    public String getComments() {
        return this.comments;
    }
    
    public void setComments(String comments) {
        this.comments = comments;
    }

    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="`customerNumber`")
    public Customers getCustomers() {
        return this.customers;
    }
    
    public void setCustomers(Customers customers) {
        this.customers = customers;
    }

    @OneToMany(fetch=FetchType.LAZY, cascade = {CascadeType.ALL}, mappedBy="orders")
    public Set<Orderdetails> getOrderdetailses() {
        return this.orderdetailses;
    }
    
    public void setOrderdetailses(Set<Orderdetails> orderdetailses) {
        this.orderdetailses = orderdetailses;
    }





    public boolean equals(Object o) {
         if (this == o) return true;
		 if ( (o == null )) return false;
		 if ( !(o instanceof Orders) )
		    return false;

		 Orders that = (Orders) o;

		 return ( (this.getOrderNumber()==that.getOrderNumber()) || ( this.getOrderNumber()!=null && that.getOrderNumber()!=null && this.getOrderNumber().equals(that.getOrderNumber()) ) );
    }

    public int hashCode() {
         int result = 17;

         result = 37 * result + ( getOrderNumber() == null ? 0 : this.getOrderNumber().hashCode() );

         return result;
    }


}

